/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGenealogyRouteImport } from './routes/dashboard/genealogy'
import { Route as DashboardInvestmentRouteImport } from './routes/dashboard/investment'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard/referrals'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardAdminAllUsersRouteImport } from './routes/dashboard/admin/all-users'
import { Route as DashboardAdminCreateUserRouteImport } from './routes/dashboard/admin/create-user'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenealogyRoute = DashboardGenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestmentRoute = DashboardInvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAllUsersRoute = DashboardAdminAllUsersRouteImport.update({
  id: '/admin/all-users',
  path: '/admin/all-users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminCreateUserRoute =
  DashboardAdminCreateUserRouteImport.update({
    id: '/admin/create-user',
    path: '/admin/create-user',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/income': typeof IncomeRoute
  '/plans': typeof PlansRoute
  '/rewards': typeof RewardsRoute
  '/dashboard/genealogy': typeof DashboardGenealogyRoute
  '/dashboard/investment': typeof DashboardInvestmentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/all-users': typeof DashboardAdminAllUsersRoute
  '/dashboard/admin/create-user': typeof DashboardAdminCreateUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/income': typeof IncomeRoute
  '/plans': typeof PlansRoute
  '/rewards': typeof RewardsRoute
  '/dashboard/genealogy': typeof DashboardGenealogyRoute
  '/dashboard/investment': typeof DashboardInvestmentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/all-users': typeof DashboardAdminAllUsersRoute
  '/dashboard/admin/create-user': typeof DashboardAdminCreateUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/income': typeof IncomeRoute
  '/plans': typeof PlansRoute
  '/rewards': typeof RewardsRoute
  '/dashboard/genealogy': typeof DashboardGenealogyRoute
  '/dashboard/investment': typeof DashboardInvestmentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/all-users': typeof DashboardAdminAllUsersRoute
  '/dashboard/admin/create-user': typeof DashboardAdminCreateUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/income'
    | '/plans'
    | '/rewards'
    | '/dashboard/genealogy'
    | '/dashboard/investment'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/admin/all-users'
    | '/dashboard/admin/create-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/income'
    | '/plans'
    | '/rewards'
    | '/dashboard/genealogy'
    | '/dashboard/investment'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/team'
    | '/dashboard'
    | '/dashboard/admin/all-users'
    | '/dashboard/admin/create-user'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/income'
    | '/plans'
    | '/rewards'
    | '/dashboard/genealogy'
    | '/dashboard/investment'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/admin/all-users'
    | '/dashboard/admin/create-user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  IncomeRoute: typeof IncomeRoute
  PlansRoute: typeof PlansRoute
  RewardsRoute: typeof RewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/genealogy': {
      id: '/dashboard/genealogy'
      path: '/genealogy'
      fullPath: '/dashboard/genealogy'
      preLoaderRoute: typeof DashboardGenealogyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investment': {
      id: '/dashboard/investment'
      path: '/investment'
      fullPath: '/dashboard/investment'
      preLoaderRoute: typeof DashboardInvestmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/all-users': {
      id: '/dashboard/admin/all-users'
      path: '/admin/all-users'
      fullPath: '/dashboard/admin/all-users'
      preLoaderRoute: typeof DashboardAdminAllUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/create-user': {
      id: '/dashboard/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/dashboard/admin/create-user'
      preLoaderRoute: typeof DashboardAdminCreateUserRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardGenealogyRoute: typeof DashboardGenealogyRoute
  DashboardInvestmentRoute: typeof DashboardInvestmentRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminAllUsersRoute: typeof DashboardAdminAllUsersRoute
  DashboardAdminCreateUserRoute: typeof DashboardAdminCreateUserRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGenealogyRoute: DashboardGenealogyRoute,
  DashboardInvestmentRoute: DashboardInvestmentRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminAllUsersRoute: DashboardAdminAllUsersRoute,
  DashboardAdminCreateUserRoute: DashboardAdminCreateUserRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  IncomeRoute: IncomeRoute,
  PlansRoute: PlansRoute,
  RewardsRoute: RewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
